name: Pre-Release

on:
  push:

jobs:

  prerelease:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: '17'
          java-package: jdk

      - name: Log into quay.io
        run: docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}" quay.io

      - name: Build&Push image
        run: |
          mvn versions:set -DnewVersion=latest
          mvn clean install deploy -DskipTests -Dimage.tag=latest -Dimage.registry="quay.io/"