name: Release

on:
  push:
    branches:
      - master

jobs:

  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: '17'
          java-package: jdk
      
      - id: pr
        uses: actions-ecosystem/action-get-merged-pull-request@v1.0.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      
      - uses: zwaldowski/semver-release-action@v2
        with:
          dry_run: true
          bump: ${{ steps.pr.outputs.labels }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Log into registry
        run: docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}" quay.io

      - name: Set version output
        id: out
        run: echo "::set-output name=version::$(echo $VERSION)"

      - name: Build image
        run: |
          mvn versions:set -DnewVersion=${{ steps.out.outputs.version }}
          mvn clean install deploy -DskipTests -Dimage.tag=${{ steps.out.outputs.version }} -Dimage.registry="quay.io/"

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ steps.out.outputs.version }}
          prerelease: false
          title: ${{ steps.out.outputs.version }}
          files: |
            LICENSE.txt
            *.jar